# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50739b6bba0004d8d58d0ec947f4ee54ce5845f68a90936236a99bc29aebfd296a900162912a7fefc742567d642c7b6160fa00c6b6b9cd40ffbf630ac17e56d6

test:
  secret_key_base: 8e5b56c7a502441c59e8a44969be0380b3d6c1fa789a57d5f11800232d6be76b230a5023b896f72a226a2621f2b5afc304c1d70c3cc31eccd1ad7a95110fe529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
